# Introduction

In this notebook, we will do a comprehensive analysis of the Android app market by comparing thousands of apps in the Google Play store.

# About the Dataset of Google Play Store Apps & Reviews

**Data Source:** <br>
App and review data was scraped from the Google Play Store by Lavanya Gupta in 2018. Original files listed [here](
https://www.kaggle.com/lava18/google-play-store-apps).

# Import Statements

In [487]:
import pandas as pd

# Notebook Presentation

In [488]:
# Show numeric output in decimal format e.g., 2.15
pd.options.display.float_format = '{:,.2f}'.format

# Read the Dataset

In [489]:
df_apps = pd.read_csv('apps.csv')

# Data Cleaning

**Challenge**: How many rows and columns does `df_apps` have? What are the column names? Look at a random sample of 5 different rows with [.sample()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html).

In [490]:
df_apps.shape
df_apps.columns
df_apps.sample(5)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
4302,HipChat - beta version,COMMUNICATION,4.10,1035,20.00,"50,000",Free,0,Everyone,Communication,"August 7, 2018",4.1 and up
9805,Checkers,GAME,4.50,375996,3.30,"10,000,000",Free,0,Everyone,Board,"August 6, 2018",4.1 and up
2997,DX Simulation for X-aid Dx Belt,FAMILY,4.00,35,48.00,"5,000",Free,0,Everyone,Simulation,"August 4, 2018",4.1 and up
2255,MC.Fitting,PRODUCTIVITY,NaN,130,3.40,"1,000",Paid,$8.49,Everyone,Productivity,"May 3, 2017",1.6 and up
310,DT CLOTHINGS,SHOPPING,5.00,1,7.90,10,Free,0,Everyone,Shopping,"July 25, 2018",4.1 and up

### Drop Unused Columns

**Challenge**: Remove the columns called `Last_Updated` and `Android_Version` from the DataFrame. We will not use these columns.

In [491]:
df_apps_new  = df_apps.drop(['Last_Updated', 'Android_Ver'], axis=1)
print(df_apps_new.columns)

Index(['App', 'Category', 'Rating', 'Reviews', 'Size_MBs', 'Installs', 'Type',
       'Price', 'Content_Rating', 'Genres'],
      dtype='object')

### Find and Remove NaN values in Ratings

**Challenge**: How may rows have a NaN value (not-a-number) in the Ratings column? Create DataFrame called `df_apps_clean` that does not include these rows.

In [492]:

print("Nan värden:", df_apps_new['Rating'].isna().sum().sum())

df_apps_new = df_apps_new.dropna(subset=['Rating'])

print("Nan värden:",df_apps_new['Rating'].isna().sum().sum())

Nan värden: 1474
Nan värden: 0

### Find and Remove Duplicates

**Challenge**: Are there any duplicates in data? Check for duplicates using the [.duplicated()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.duplicated.html) function. How many entries can you find for the "Instagram" app? Use [.drop_duplicates()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html) to remove any duplicates from `df_apps_clean`.

In [493]:

instagram_rows = df_apps_new[df_apps_new['App'] == 'Instagram']["App"].count()
print("Rader för Instagram-appar:",instagram_rows)

print("Antal dubletter:",df_apps_new.duplicated().sum())

df_apps_new = df_apps_new.drop_duplicates()

print("Antal dubletter:",df_apps_new.duplicated().sum())

Rader för Instagram-appar: 4
Antal dubletter: 476
Antal dubletter: 0

# Find Highest Rated Apps

**Challenge**: Identify which apps are the highest rated. What problem might you encounter if you rely exclusively on ratings alone to determine the quality of an app?

In [494]:
df_apps_new.sort_values('Rating', ascending=False).head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
186,Basics of Orthopaedics,MEDICAL,5.00,1,5.60,10,Free,0,Everyone,Medical
21,KBA-EZ Health Guide,MEDICAL,5.00,4,25.00,1,Free,0,Everyone,Medical
28,Ra Ga Ba,GAME,5.00,2,20.00,1,Paid,$1.49,Everyone,Arcade
47,Mu.F.O.,GAME,5.00,2,16.00,1,Paid,$0.99,Everyone,Arcade
237,EC Mover,GAME,5.00,5,4.60,10,Free,0,Everyone,Racing

# Find 5 Largest Apps in terms of Size (MBs)

**Challenge**: What's the size in megabytes (MB) of the largest Android apps in the Google Play Store. Based on the data, do you think there could be limit in place or can developers make apps as large as they please?

In [495]:
df_apps_new.sort_values('Size_MBs', ascending=False).head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
9945,Ultimate Tennis,SPORTS,4.30,183004,100.00,"10,000,000",Free,0,Everyone,Sports
9944,Gangster Town: Vice District,FAMILY,4.30,65146,100.00,"10,000,000",Free,0,Mature 17+,Simulation
9943,Miami crime simulator,GAME,4.00,254518,100.00,"10,000,000",Free,0,Mature 17+,Action
9942,Talking Babsy Baby: Baby Games,LIFESTYLE,4.00,140995,100.00,"10,000,000",Free,0,Everyone,Lifestyle;Pretend Play
10687,Hungry Shark Evolution,GAME,4.50,6074334,100.00,"100,000,000",Free,0,Teen,Arcade

# Find the 5 App with Most Reviews

**Challenge**: Which apps have the highest number of reviews? Are there any paid apps among the top 50?

In [496]:
df_apps_new.sort_values('Reviews', ascending=False).head()

top50 = df_apps_new.sort_values('Reviews', ascending=False).head(50)


print("50 med högs betyg som är gratis/kostar:",top50['Type'].value_counts())

50 med högs betyg som är gratis/kostar: Type
Free    50
Name: count, dtype: int64

# Plotly Pie and Donut Charts - Visualise Categorical Data: Content Ratings

In [497]:
import plotly.express as px


ratings_count = df_apps_new['Content_Rating'].value_counts()


fig = px.pie(
    values=ratings_count.values,
    names=ratings_count.index,
    title='Content Ratings'
)

fig.show()

# Numeric Type Conversion: Examine the Number of Installs

**Challenge**: How many apps had over 1 billion (that's right - BILLION) installations? How many apps just had a single install?

Check the datatype of the Installs column.

Count the number of apps at each level of installations.

Convert the number of installations (the Installs column) to a numeric data type. Hint: this is a 2-step process. You'll have make sure you remove non-numeric characters first.

In [498]:
df_apps_new['Installs'].dtype

df_apps_new['Installs'] = df_apps_new['Installs'].str.replace(',', '').str.replace('+', '').str.replace('Free', '0')
df_apps_new['Installs'] = pd.to_numeric(df_apps_new['Installs'])
df_apps_new[df_apps_new['Installs'] >= 1_000_000_000].shape[0]
df_apps_new[df_apps_new['Installs'] == 1].shape[0]
df_apps_new['Installs'].value_counts().head()

Installs
1000000     1486
10000000    1130
100000      1110
10000        989
1000         699
Name: count, dtype: int64

# Find the Most Expensive Apps, Filter out the Junk, and Calculate a (ballpark) Sales Revenue Estimate

Let's examine the Price column more closely.

**Challenge**: Convert the price column to numeric data. Then investigate the top 20 most expensive apps in the dataset.

Remove all apps that cost more than $250 from the `df_apps_clean` DataFrame.

Add a column called 'Revenue_Estimate' to the DataFrame. This column should hold the price of the app times the number of installs. What are the top 10 highest grossing paid apps according to this estimate? Out of the top 10 highest grossing paid apps, how many are games?

### The most expensive apps sub $250

In [499]:

df_apps_new['Price'] = df_apps_new['Price'].str.replace('$', '')
df_apps_new['Price'] = pd.to_numeric(df_apps_new['Price'])


print("Top 20 dyraste appar:",df_apps_new.sort_values('Price', ascending=False).head(20))

df_apps_new = df_apps_new[df_apps_new['Price'] <= 250]

print("Appar kvar efter att ha tagit bort dyra appar:", df_apps_new.shape)


df_apps_new['Revenue_Estimate'] = df_apps_new['Price'] * df_apps_new['Installs']
top10 = df_apps_new.sort_values('Revenue_Estimate', ascending=False).head(10)
print("Top 10 högst intäkter:",top10)


games_count = top10[top10['Category'] == 'GAME'].shape[0]

print("Antal spel i top 10:", games_count)

Top 20 dyraste appar:                                  App   Category  Rating  Reviews  Size_MBs  \
3946        I'm Rich - Trump Edition  LIFESTYLE    3.60      275      7.30
1331          most expensive app (H)     FAMILY    4.30        6      1.50
1946  I am rich (Most expensive app)    FINANCE    4.10      129      2.70
2461              I AM RICH PRO PLUS    FINANCE    4.00       36     41.00
5765                       I am rich  LIFESTYLE    3.80     3547      1.80
3221                  I am Rich Plus     FAMILY    4.00      856      8.70
2394                      I am Rich!    FINANCE    3.80       93     22.00
4606               I Am Rich Premium    FINANCE    4.10     1867      4.70
3114                       I am Rich    FINANCE    4.30      180      3.80
3145              I am rich(premium)    FINANCE    3.50      472      0.94
2775                   I Am Rich Pro     FAMILY    4.40      201      2.70
3554                      💎 I'm rich  LIFESTYLE    3.80      718     26.00
3897                       I Am Rich     FAMILY    3.60      217      4.90
2193             I am extremely Rich  LIFESTYLE    2.90       41      2.90
3856                   I am rich VIP  LIFESTYLE    3.80      411      2.60
2281       Vargo Anesthesia Mega App    MEDICAL    4.60       92     32.00
1407                    LTC AS Legal    MEDICAL    4.00        6      1.30
2629                I am Rich Person  LIFESTYLE    4.20      134      1.80
2481         A Manual of Acupuncture    MEDICAL    3.50      214     68.00
2207                        EMT PASS    MEDICAL    3.40       51      2.40

      Installs  Type  Price Content_Rating         Genres
3946     10000  Paid 400.00       Everyone      Lifestyle
1331       100  Paid 399.99       Everyone  Entertainment
1946      1000  Paid 399.99           Teen        Finance
2461      1000  Paid 399.99       Everyone        Finance
5765    100000  Paid 399.99       Everyone      Lifestyle
3221     10000  Paid 399.99       Everyone  Entertainment
2394      1000  Paid 399.99       Everyone        Finance
4606     50000  Paid 399.99       Everyone        Finance
3114      5000  Paid 399.99       Everyone        Finance
3145      5000  Paid 399.99       Everyone        Finance
2775      5000  Paid 399.99       Everyone  Entertainment
3554     10000  Paid 399.99       Everyone      Lifestyle
3897     10000  Paid 389.99       Everyone  Entertainment
2193      1000  Paid 379.99       Everyone      Lifestyle
3856     10000  Paid 299.99       Everyone      Lifestyle
2281      1000  Paid  79.99       Everyone        Medical
1407       100  Paid  39.99       Everyone        Medical
2629      1000  Paid  37.99       Everyone      Lifestyle
2481      1000  Paid  33.99       Everyone        Medical
2207      1000  Paid  29.99       Everyone        Medical
Appar kvar efter att ha tagit bort dyra appar: (8876, 10)
Top 10 högst intäkter:                                 App     Category  Rating  Reviews  Size_MBs  \
9224                      Minecraft       FAMILY    4.50  2375336     19.00
9220                      Minecraft       FAMILY    4.50  2376564     19.00
8825                  Hitman Sniper         GAME    4.60   408292     29.00
7151  Grand Theft Auto: San Andreas         GAME    4.40   348962     26.00
7977        Sleep as Android Unlock    LIFESTYLE    4.50    23966      0.85
7477            Facetune - For Free  PHOTOGRAPHY    4.40    49553     48.00
6594            DraStic DS Emulator         GAME    4.60    87766     12.00
6082                   Weather Live      WEATHER    4.50    76593      4.75
7954                    Bloons TD 5       FAMILY    4.60   190086     94.00
7633        Five Nights at Freddy's         GAME    4.60   100805     50.00

      Installs  Type  Price Content_Rating                     Genres  \
9224  10000000  Paid   6.99   Everyone 10+  Arcade;Action & Adventure
9220  10000000  Paid   6.99   Everyone 10+  Arcade;Action & Adventure
8825  10000000  Paid   0.99     Mature 17+                     Action
7151   1000000  Paid   6.99     Mature 17+                     Action
7977   1000000  Paid   5.99       Everyone                  Lifestyle
7477   1000000  Paid   5.99       Everyone                Photography
6594   1000000  Paid   4.99       Everyone                     Action
6082    500000  Paid   5.99       Everyone                    Weather
7954   1000000  Paid   2.99       Everyone                   Strategy
7633   1000000  Paid   2.99           Teen                     Action

      Revenue_Estimate
9224     69,900,000.00
9220     69,900,000.00
8825      9,900,000.00
7151      6,990,000.00
7977      5,990,000.00
7477      5,990,000.00
6594      4,990,000.00
6082      2,995,000.00
7954      2,990,000.00
7633      2,990,000.00
Antal spel i top 10: 4

# Plotly Bar Charts & Scatter Plots: Analysing App Categories

### Vertical Bar Chart - Highest Competition (Number of Apps)

In [500]:
cat_counts = df_apps_new['Category'].value_counts()

print("Top 10 kategorier med flest appar:")
print(cat_counts.head(10))

fig = px.bar(
    x=cat_counts.index,
    y=cat_counts.values,
    labels={'x': 'Kategori', 'y': 'Antal appar'},
    title="Konkurrens: Antal appar per kategori"
)
fig.show()

Top 10 kategorier med flest appar:
Category
FAMILY             1714
GAME               1074
TOOLS               733
PRODUCTIVITY        334
FINANCE             311
PERSONALIZATION     310
COMMUNICATION       307
PHOTOGRAPHY         304
MEDICAL             302
LIFESTYLE           301
Name: count, dtype: int64

### Horizontal Bar Chart - Most Popular Categories (Highest Downloads)

In [501]:
cat_installs = df_apps_new.groupby('Category')['Installs'].sum().sort_values(ascending=True)

print("Top 10 kategorier med flest nerladdningar:")
print(cat_installs.tail(10))

fig = px.bar(
    x=cat_installs.values,
    y=cat_installs.index,
    orientation='h',
    labels={'x': 'Antal nerladdningar', 'y': 'Kategori'},
    title="Popularitet: Antal nerladdningar per kategori"
)

fig.show()

Top 10 kategorier med flest nerladdningar:
Category
NEWS_AND_MAGAZINES     5393110650
VIDEO_PLAYERS          6221897200
TRAVEL_AND_LOCAL       6361859300
PHOTOGRAPHY            9721243130
FAMILY                10041105490
TOOLS                 11440724500
PRODUCTIVITY          12463070180
SOCIAL                12513841475
COMMUNICATION         24152241530
GAME                  31543862717
Name: Installs, dtype: int64

### Category Concentration - Downloads vs. Competition

**Challenge**:
* First, create a DataFrame that has the number of apps in one column and the number of installs in another:

<img src=https://imgur.com/uQRSlXi.png width="350">

* Then use the [plotly express examples from the documentation](https://plotly.com/python/line-and-scatter/) alongside the [.scatter() API reference](https://plotly.com/python-api-reference/generated/plotly.express.scatter.html)to create scatter plot that looks like this.

<img src=https://imgur.com/cHsqh6a.png>

*Hint*: Use the size, hover_name and color parameters in .scatter(). To scale the yaxis, call .update_layout() and specify that the yaxis should be on a log-scale like so: yaxis=dict(type='log')

In [502]:
import plotly.express as px

cat_data = df_apps_new.groupby('Category').agg(
    Apps=('App', 'count'),
    Installs=('Installs', 'sum')
).reset_index()

print(cat_data.head())

fig = px.scatter(
    cat_data,
    x='Apps',
    y='Installs',
    size='Installs',
    color='Category',
    hover_name='Category',
    title='Nedladdningar vs konkurrens'
)

fig.update_layout(
    yaxis=dict(type='log')
)

fig.show()

              Category  Apps    Installs
0       ART_AND_DESIGN    62   124233100
1    AUTO_AND_VEHICLES    73    53129800
2               BEAUTY    42    26916200
3  BOOKS_AND_REFERENCE   177  1916291655
4             BUSINESS   270   863518120